import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  theme: {
    screens: {
      sm: '393px',
      md: '744px',
      lg: '1440px',
    },
    extend: {
      colors: {
        base: '#07080f',
        surface: '#0e1017',
        'input-bg': '#1a1c27',
        green: '#5DCAA5',
        amber: '#EF9F27',
        danger: '#e24b4a',
        'primary-50': '#f5f4fb',
        'primary-100': '#e1def1',
        'primary-200': '#d3ceea',
        'primary-300': '#bfb7e1',
        'primary-400': '#b2a9db',
        'primary-500': '#9f94d2',
        'primary-600': '#9187bf',
        'primary-700': '#716995',
        'primary-800': '#575174',
        'primary-900': '#433e58',
        'primary-dark-50': '#e6e6e7',
        'primary-dark-100': '#b0b1b6',
        'primary-dark-200': '#8a8b92',
        'primary-dark-300': '#555660',
        'primary-dark-400': '#343541',
        'primary-dark-500': '#010312',
        'primary-dark-600': '#010310',
        'primary-dark-700': '#01020d',
        'primary-dark-800': '#01020a',
        'primary-dark-900': '#000108',
      },
      fontFamily: {
        sans: ['var(--font-geist-sans)', 'sans-serif'],
        pixel: ['var(--font-geist-pixel-square)', 'monospace'],
      },
      fontSize: {
        's': ['12px', { lineHeight: '20px', letterSpacing: '-0.02em' }],
        'm': ['14px', { lineHeight: '20px', letterSpacing: '-0.02em' }],
        'l': ['16px', { lineHeight: '24px', letterSpacing: '-0.02em' }],
        'xl': ['18px', { lineHeight: '24px', letterSpacing: '-0.02em' }],
        'h6': ['20px', { lineHeight: '24px', letterSpacing: '-0.04em' }],
        'h5': ['24px', { lineHeight: '32px', letterSpacing: '-0.04em' }],
        'h4': ['36px', { lineHeight: '44px', letterSpacing: '-0.04em' }],
        'h3': ['48px', { lineHeight: '56px', letterSpacing: '-0.04em' }],
        'h2': ['56px', { lineHeight: '64px', letterSpacing: '-0.04em' }],
        'h1': ['64px', { lineHeight: '72px', letterSpacing: '-0.06em' }],
        'h1-mobile': ['48px', { lineHeight: '56px', letterSpacing: '-0.06em' }],
        'h2-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.04em' }],
        'h3-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.04em' }],
        'h4-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.04em' }],
      },
      borderRadius: {
        'button': '100px',
        'input': '12px',
        'card': '12px',
        'badge': '100px',
        'tab': '12px',
        'inner': '8px',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
      spacing: {
        'section': '120px',
        'section-tablet': '80px',
        'section-mobile': '60px',
        'inner-lg': '48px',
        'inner-md': '24px',
        'inner-sm': '12px',
        'card-pad': '24px',
        'card-pad-mobile': '16px',
      },
    },
  },
}

export default config
